# Generated by Django 3.2.8 on 2021-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_instrument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
